set nocompatible              " be iMproved, required
filetype off                  " required
if has('nvim')
	set termguicolors
endif
" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" alternatively, pass a path where Vundle should install plugins
"call vundle#begin('~/some/path/here')

" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'

if !has('nvim')
	Plugin 'tpope/vim-sensible'
endif

Plugin 'tpope/vim-sleuth'
Plugin 'altercation/vim-colors-solarized'
Plugin 'bling/vim-airline'
Plugin 'lambdalisue/vim-manpager'
Plugin 'fidian/hexmode'

" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required

" http://stackoverflow.com/a/17362994/5279817
" size of a hard tabstop
set tabstop=2
" always uses spaces instead of tab characters
set expandtab
" size of an "indent"
set shiftwidth=2

" based on https://github.com/derElektrobesen/dotfiles/blob/master/.vimrc
set list
set listchars=tab:>-,trail:-

set number
" set relativenumber

" Break on words, not letters (when displaying)
" set linebreak
" as much as possible of the last line in a window will be displayed (not @)
set display=lastline

" Tell vim to remember certain things when we exit
"  '50  :  marks will be remembered for up to 10 previously edited files
"  "100 :  will save up to 100 lines for each register
"  :20  :  up to 20 lines of command-line history will be remembered
"  %    :  saves and restores the buffer list
"  n... :  where to save the viminfo files

if has('nvim')
	set viminfo='50,\"100,:20,%,n~/.vim/nviminfo
endif

set textwidth=72

set smartcase
set ignorecase

