# add homebrew zsh site-functions to fpath -- required on apple silicon
# macOS due to homebrew not being in /usr/local
if (( $+commands[brew] )); then
  brew_prefix=${HOMEBREW_PREFIX:-${HOMEBREW_REPOSITORY:-$commands[brew]:A:h:h}}
  [[ $brew_prefix == '/usr/local/Homebrew' ]] && brew_prefix=$brew_prefix:h
  fpath+=($brew_prefix/share/zsh/site-functions(/N))
  unset brew_prefix
fi

fpath=(
  ~/.zfunc(/N)
  $fpath
  "${HOME}/dotfiles/zsh/zfunc"(/N)
)

[ -f ~/.zsh-init.local ] && source ~/.zsh-init.local || true

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

alias sudo="sudo "

# Shortcuts
alias ls="eza"
alias vim="nvim"

# Git aliases
alias g='git'
alias ga='git add'
alias gap='git add -p'
alias gb='git branch'
alias gc='git checkout'
alias gd='git diff'
alias gl='git hist'
alias gm='git commit -m'
alias gp='git push'
alias gs='git status'
alias gss='git status -sb'

# `cd` to Git repo root
alias gr='[ ! -z `git rev-parse --show-cdup` ] && cd `git rev-parse --show-cdup || pwd`'

# fancy diff
alias fdiff="git diff --color --no-index "

function mdcd() {
  mkdir -p "$@" && cd "$@"
}

__copy_function() {
  test -n "$(declare -f "$1")" || return
  eval "${_/$1/$2}"
}

__rename_function() {
  copy_function "$@" || return
  unset -f "$1"
}

# if there's ~/.venv -- activate it and hide prompt for it
# however, disable_prompt should be unset when running deactivate
# so wrap original deactivate function
if [ -f ~/.venv/bin/activate ]; then
  export VIRTUAL_ENV_DISABLE_PROMPT=1
  source ~/.venv/bin/activate

  __copy_function deactivate __deactivate
  deactivate() {
    __deactivate
    unset -f __deactivate
    unset VIRTUAL_ENV_DISABLE_PROMPT
  }
fi

autoload -Uz _extended_logout_setup && _extended_logout_setup

[ -f ~/.zsh.local ] && source ~/.zsh.local || true
